---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-sample-nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: docker-sample-nginx
    spec:
      containers:
      - name: docker-sample-nginx
        image: gvirtuoso/docker-sample-nginx:latest
        ports:
        - name: nginx-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: nginx-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: nginx-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: docker-sample-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30304
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: docker-sample-nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-sample-nginx-rules
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - app.prod-k8s.guilhermevirtuoso.com
    secretName: docker-sample-nginx-tls-cert
  rules:
  - host: app.prod-k8s.guilhermevirtuoso.com
    http:
      paths:
      - path: /
        backend:
          serviceName: docker-sample-nginx
          servicePort: 80
